
version: 2

models:
    - name: int_orders
      description: "A starter dbt model"
      columns:
          - name: pk_order_key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null